<div class="hero-unit">
    <h1><?php echo $this->translate('Design for humans') ?></h1>
    <p><?php echo $this->translate("Find or add a challenge and design an innovative solution.") ?></p>
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('New challenges') ?></h2>
        <p><?php echo $this->translate('Tell the community about your experiences or split the challenge into smaler challenges.') ?></p>
        <ul><li>How to do this?</li></ul>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Ideate solutions') ?></h2>
        <p><?php echo $this->translate('Add, improve or vote community ideas.') ?></p>
        <ul><li>How can we do this?</li></ul>
    </div>
    
</div>
