<div class="hero-unit">
	<h1>
		<?php echo $this->translate('Challenges') ?>
	</h1>
	<p>
		<?php echo $this->translate("Find or add a challenge and design an innovative solution.") ?>
	</p>
</div>

<div class="row">

	<div class="span4">
		<h2><?php echo $this->translate('New challenges') ?></h2>
		<p><?php echo $this->translate('Tell the community about your experiences or split the challenge into smaler challenges.') ?></p>
		<?php if (count($lastChallenges)>0): ?>
		<ul>
			<?php foreach ($lastChallenges as $challenge): ?>
			<li><?php $this->escapeHtml($challenge->challenge) ?> - <?php $this->escapeHtml(date("Y-m-d", strtotime($challenge->dateAdded))) ?></li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
	</div>

</div>
